[kubemonkey]
dry_run = false                          # Terminations are only logged if true
run_hour = 8                             # Run scheduling at 8am on weekdays
start_hour = 10                          # Don't schedule any pod deaths before 10am
end_hour = 16                            # Don't schedule any pod deaths after 4pm
blacklisted_namespaces = ["kube-system"] # Critical apps live here
whitelisted_namespaces = ["corpora"]     # Where we allow kube-monkey to kill pods.
time_zone = "Europe/Stockholm"           # Set tzdata timezone example. Note the field is time_zone not timezone

[debug]
enabled = true                            # Debug mode is enabled
schedule_immediate_kill = true            # Kill when we start the pod (for debug purposes)
